### ISSUE TITLE
Error: Cannot find module 'trash'

### ISSUE THREAD

**Issue by ghost** [VideoExpertsGroup/Chrome-RTSP-Player#11]
openSUSE 42.2

[install.txt](https://github.com/VideoExpertsGroup/Chrome-RTSP-Player/files/1164589/install.txt)

[run_build.txt](https://github.com/VideoExpertsGroup/Chrome-RTSP-Player/files/1164592/run_build.txt)

[npm-debug.txt](https://github.com/VideoExpertsGroup/Chrome-RTSP-Player/files/1164595/npm-debug.txt)

**Comment by bleikher** [comment]
Hi,

Could you please check that 
the folder 'node_modules' contains the 'trash' folder?
I used npm@3.6.0 version.

Thanks,
Alexey Bleikher
Solution Architect | VXG
www.videoexpertsgroup.com

**Comment by hellochenwang** [comment]
I got the same problem.

```
stovetop-2:Chrome-RTSP-Player nw$ npm install
npm WARN package.json directory-copy@0.1.0 No repository field.
npm WARN package.json fs@0.0.2 fs is also the name of a node core module.
npm WARN package.json fs@0.0.2 No description
npm WARN package.json fs@0.0.2 No repository field.
npm WARN package.json fs@0.0.2 No README data
npm WARN package.json uglify-js@2.2.0 'repositories' (plural) Not supported. Please pick one as the 'repository' field
stovetop-2:Chrome-RTSP-Player nw$ npm run build

> vxgplayer@1.8.2 build /Users/nw/Chrome-RTSP-Player
> node build.js %npm_package_version% $npm_package_version

module.js:338
    throw err;
          ^
Error: Cannot find module 'trash'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/nw/Chrome-RTSP-Player/build.js:7:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! code ELIFECYCLE
npm ERR! vxgplayer@1.8.2 build: `node build.js %npm_package_version% $npm_package_version`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vxgplayer@1.8.2 build script 'node build.js %npm_package_version% $npm_package_version'.
npm ERR! This is most likely a problem with the vxgplayer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js %npm_package_version% $npm_package_version
npm ERR! You can get their info via:
npm ERR!     npm owner ls vxgplayer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nw/Chrome-RTSP-Player/npm-debug.log
stovetop-2:Chrome-RTSP-Player nw$ ls
API.md		README.md	build.js	node_modules	npm-debug.log	package.json	src
stovetop-2:Chrome-RTSP-Player nw$ cd node_modules/
stovetop-2:node_modules nw$ ls
babelify	browserify-shim	copyfiles	fs		mkdirp		node-zip	renamer		trash-cli
browserify	clean-css	directory-copy	markdown-html	node-markdown	promise		replace		uglify-js
stovetop-2:node_modules nw$ 
```

**Comment by hellochenwang** [comment]
Updated Node to the latest version v6.11.2, still missing trash module

installed trash module:
npm install --save trash

worked.
